project/models.py
# -*- coding: utf-8 -*-

from .auth.models import User

project/__init__.py
from .app import create_app, create_celery

project/api/__init__.py
# -*- coding: utf-8 -*-

from .views import *

project/api/views.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, render_template, current_app)

from ..extensions import manager
# from ..models import MyModel


def initialize_api(app):
    with app.app_context():
        # List all Flask-Restless APIs here
        # model_api = manager.create_api(MyModel, methods=['GET'],
        #                                app=app,
        #                                url_prefix='/api')
        pass


api = Blueprint('api', __name__)

project/app.py
# -*- coding: utf-8 -*-
# pylint:disable-msg=W0612

import os
from flask import Flask, request, render_template, g
from flask_login import current_user
from celery import Celery

from .extensions import (
    db,
    mail,
    pages,
    manager,
    login_manager,
    babel,
    migrate,
    csrf,
    cache,
    celery,
)

# blueprints
from .frontend import frontend
from .auth import auth
from .api import api, initialize_api

from social.apps.flask_app.routes import social_auth
from social.apps.flask_app.default.models import init_social
from social.apps.flask_app.template_filters import backends

__all__ = ("create_app", "create_celery")

BLUEPRINTS = (frontend, social_auth, auth, api)


def create_app(config=None, app_name="project", blueprints=None):
    app = Flask(
        app_name,
        static_folder=os.path.join(os.path.dirname(__file__), "..", "static"),
        template_folder="templates",
    )

    app.config.from_object("project.config")
    app.config.from_pyfile("../local.cfg", silent=True)
    if config:
        app.config.from_pyfile(config)

    if blueprints is None:
        blueprints = BLUEPRINTS

    blueprints_fabrics(app, blueprints)
    extensions_fabrics(app)
    api_fabrics(api)  # this must be called after extensions_fabrics
    configure_logging(app)

    error_pages(app)
    gvars(app)

    return app


def create_celery(app):
    celery = Celery(app.import_name, broker=app.config["CELERY_BROKER_URL"])
    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask
    return celery


def blueprints_fabrics(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def extensions_fabrics(app):
    db.init_app(app)
    mail.init_app(app)
    babel.init_app(app)
    pages.init_app(app)
    init_social(app, db)
    login_manager.init_app(app)
    manager.init_app(app, flask_sqlalchemy_db=db)
    migrate.init_app(app, db)
    csrf.init_app(app)
    cache.init_app(app)
    celery.config_from_object(app.config)


def api_fabrics(app):
    # initialize_api(app)
    pass


def error_pages(app):
    # HTTP error pages definitions

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("misc/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("misc/404.html"), 404

    @app.errorhandler(405)
    def method_not_allowed(error):
        return render_template("misc/405.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("misc/500.html"), 500


def gvars(app):
    @app.before_request
    def gdebug():
        if app.debug:
            g.debug = True
        else:
            g.debug = False

    app.context_processor(backends)

    from .models import User

    @login_manager.user_loader
    def load_user(userid):
        try:
            return User.query.get(int(userid))
        except (TypeError, ValueError):
            pass

    @app.before_request
    def guser():
        g.user = current_user

    @app.context_processor
    def inject_user():
        try:
            return {"user": g.user}
        except AttributeError:
            return {"user": None}

    @babel.localeselector
    def get_locale():
        if g.user:
            if hasattr(g.user, "ui_lang"):
                return g.user.ui_lang

        accept_languages = app.config.get("ACCEPT_LANGUAGES")
        return request.accept_languages.best_match(accept_languages)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config["LOG_FOLDER"], "info.log")
    info_file_handler = logging.handlers.RotatingFileHandler(
        info_log, maxBytes=100000, backupCount=10
    )
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(
        logging.Formatter(
            "%(asctime)s %(levelname)s: %(message)s " "[in %(pathname)s:%(lineno)d]"
        )
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    # app.logger.info("testing info.")
    # app.logger.warn("testing warn.")
    # app.logger.error("testing error.")

    mail_handler = logging.handlers.SMTPHandler(
        app.config["MAIL_SERVER"],
        app.config["MAIL_USERNAME"],
        app.config["ADMINS"],
        "O_ops... %s failed!" % app.config["PROJECT"],
        (app.config["MAIL_USERNAME"], app.config["MAIL_PASSWORD"]),
    )
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(
        logging.Formatter(
            "%(asctime)s %(levelname)s: %(message)s " "[in %(pathname)s:%(lineno)d]"
        )
    )
    app.logger.addHandler(mail_handler)

project/frontend/__init__.py
from .views import frontend

project/frontend/views.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, render_template, g, request, url_for,
    current_app, send_from_directory, json, redirect, make_response, abort)

from flask_login import login_required

from ..extensions import pages, csrf
from ..tasks import do_some_stuff

frontend = Blueprint('frontend', __name__, template_folder="templates")


@frontend.route('/')
def index():
    # Run background task inside of view
    do_some_stuff.delay()
    return render_template('frontend/index.html')


@frontend.route('/docs/', defaults={'path': 'index'})
@frontend.route('/docs/<path:path>/', endpoint='page')
def page(path):
    # Documentation views
    _page = pages.get_or_404(path)
    return render_template('page.html', page=_page)


@frontend.route('/robots.txt')
def static_from_root():
    # Static items
    return send_from_directory(current_app.static_folder, request.path[1:])


@frontend.route('/favicon.ico')
def favicon():
    return redirect('/static/favicon.png')

project/frontend/templates/frontend/index.html
{% extends "base.html" %}
{% set page_title = _('Welcome to our new site') %}

{% block content %}
  <h1>{{ _("Welcome to our new site") }}</h1>
  <p>This is special splash page.</p>

{% endblock %}

project/frontend/templates/frontend/splash.html
{% extends "base.html" %}
{% set page_title = _('Welcome to our new site') %}

{% block content %}
  <h1>{{ _("Welcome to our new site") }}</h1>
  <p>This is special splash page.</p>

{% endblock %}

project/frontend/templates/frontend/user_profile.html
{% extends "base.html" %}
{% set page_title = user_profile.name %}

{% block include_css %}
{# <link rel="stylesheet" href="/static/libs/" type="text/css" media="screen"/> #}
{% endblock %}

{% block include_js %}
{# <script src="/static/libs/"></script> #}
{% endblock %}

{% block content %}
  <h1>{{ user_profile.name }}</h1>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="{{ lang|default("en") }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/favicon.png">

  <title>{% block title %}{{ page_title|default(_('New site')) }}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap/dist/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">
  {% block include_css %}
  {% endblock %}
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <script src="{{ url_for('static', filename='libs/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='code.js') }}"></script>
  {% block include_js %}
  {% endblock %}

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
{% block extramedia %}{% endblock %}
{% include "counter.html" %}

</head>
<body {% block body_id %}{% endblock %}>
<div id="wrap">

  {% include "nav.html" %}

  {% block fullcontent %}

  <div class="container">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {# Body #}
    {% block content %}{% endblock %}
  </div>
  {% endblock %}

</div> <!-- /wrap -->

<div id="footer">
  <div class="container">
    <p>&copy; 2014 <a href="{{ url_for('frontend.index', _external=True) }}">{{_("New site")}}</a></p>
  </div>
</div>

</body>
</html>

project/templates/counter.html
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXX']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

project/templates/macros.html
{% macro render_bootstrap_field(field) %}

<div class="form-group {% if field.errors %} has-error {% endif %}">
  <label class="col-sm-2 col-lg-2 control-label" for="{{field.id}}">{{ field.label }}</label>

  <div class="col-lg-8 col-sm-8">
    {{ field(class='form-control')|safe }}
    {% if field.errors %}
      {% for error in field.errors %}
        <span class="help-block">{{ error }}</span><br>
      {% endfor %}
    {% endif %}
    {% if field.description %}
      <span class="help-block">{{field.description}}</span>
    {% endif %}
  </div>
</div>
{% endmacro %}

project/templates/misc/405.html
{% extends "misc/base.html" %}
{% set page_title = _('Method not allowed') %}
{% block content %}
<h1>{{ _("Error 405") }}</h1>
<p class="lead">{{_("You are trying to access page by methods that is not allowed.")}}</p>
<p><a href="/">{{ _("&larr; Back to front page") }}</a></p>
{% endblock %}

project/templates/misc/base.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block js_btm %}
{% endblock %}

project/templates/nav.html
<!-- Static navbar -->
<div class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand {% if url_for('frontend.index') == request.path %}active{% endif %}" href="{{ url_for('frontend.index') }}">{{ _("Site") }}</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li {% if url_for('frontend.index') == request.path %}class="active"{% endif %}><a href="{{ url_for('frontend.index') }}">{{ _("Splash page") }}</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li {% if url_for('frontend.page') == request.path %}class="active"{% endif %}><a href="{{ url_for('frontend.page') }}"><i class="fa fa-book"></i> {{ _("About site ") }}</a></li>

      {% if user.is_authenticated() %}
      <li><a href="{{ url_for('auth.settings') }}">{{ _("Settings")}}</a></li>
      <li><a href="{{ url_for('auth.logout') }}" data-confirm="{{ _('Do you want to logout?')}}" data-title="{{ _('Logout?') }}"><i class="fa fa-sign-out"></i> {{ _("Logout") }}</a></li>
      {% else %}
      <li><a href="{{ url_for('auth.login') }}"> {{ _("Login") }} </a></li>
      {% endif %}

    </ul>
  </div><!--/.nav-collapse -->
</div>

project/templates/page.html
{% extends "base.html" %}
{% set page_title = page.title %}

{% block content %}

{{ page.html|safe }}

{% endblock %}